[package]
name = "pypackages"
version = "0.0.1"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "^0.4.13"
regex = "^1.1.9"
reqwest = "^0.9.19"
structopt = "^0.2.18"
serde = {version = "^1.0.92", features = ["derive"]}
toml = "^0.5.1"
#solvent = "0.8.1"