[package]
name = "pypackages"
version = "0.0.1"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"
regex = "^1.1.9"
structopt = "^0.2.18"
serde = {version = "^1.0.92", features = ["derive"]}
#text_io = "^0.1.7"
toml = "^0.5.1"