[tool.pypackage]
name = "aname"
py_version = "3.7"
version = "0.1.0"
description = "Good job!"
author = "David O'Connor"


[tool.pypackage.dependencies]
siunits = "0.0.4"
saturn = "0.3.4"
numpy = "1.15.2"
fplot = "0.2.3"
#matplotlib = "3.1.1"
